### ISSUE TITLE
添加环境

### ISSUE THREAD

**Issue by bamtercelboo** [thunlp/CAIL#12]
您好：
能不能添加python-3.6.3，pytorch-0.3.0
谢谢

**Comment by xcjthu** [comment]
python3.6 和 现在提供的 python3.5 差别不是很大
pytorch已经提供了 0.3.1 和 0.3.0的接口基本相同，但是修复了一些bug，所以还是建议使用pytorch0.3.1

**Comment by tongjinle123** [comment]
我用的0.4.0怎么办 我的代码已经写完了

**Comment by xcjthu** [comment]
对于0.4.0我们会有专门的选项进行选择，这个适合 pytorch0.3.1冲突选项，所以会单独处理
