### ISSUE TITLE
label不一致问题

### ISSUE THREAD

**Issue by congqinghe** [thunlp/CAIL#15]
您好，那个任务一罪名预测是需要提交真实的罪名，而我发现训练集的label给的与你们给的罪名文件不太一样，
比如 accu文件中给定的是：组织、强迫、引诱、容留、介绍卖淫
而训练集的label给定的是：[组织、强迫、引诱、容留、介绍]卖淫
这样的话我们提交的结果该如何处理？

**Comment by tongjinle123** [comment]
补充一下 存在这样的情况：label: 
'accusation': ['故意伤害', '盗窃', '[组织、强迫、引诱、容留、介绍]卖淫', '[引诱、容留、介绍]卖淫'],

**Comment by xcjthu** [comment]
关于结果的提交请参考：[代码提交说明](https://github.com/thunlp/CAIL2018)，里面进行了详细的阐述

关于accusation中的罪名不存在的问题，我们检查一遍数据后未发现有该问题，请问能提供更加详细的内容嘛

**Comment by tongjinle123** [comment]
import json

f=open('raw_data/cail2018_small/data_train.json')

data = f.readlines()

json.loads(data[0])#['meta']['accusation'][0][-2:]

for i in data:
    line = json.loads(i)
    accusations = line['meta']['accusation']
    for i in accusations:
        if i[-2:] == '卖淫':
            print(i)

**Comment by tongjinle123** [comment]
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
强迫卖淫
[组织、强迫、引诱、容留、介绍]卖淫
强迫卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
组织卖淫
[组织、强迫、引诱、容留、介绍]卖淫
[引诱、容留、介绍]卖淫
[组织、强迫、引诱、容留、介绍]卖淫
组织卖淫

**Comment by tongjinle123** [comment]
检查后发现
[组织、强迫、引诱、容留、介绍]卖淫 和 [引诱、容留、介绍]卖淫' 属于不同的两个罪名，是我看错了
