### ISSUE TITLE
法条预测label重复出现的情况

### ISSUE THREAD

**Issue by wangtianyiftd** [thunlp/CAIL#16]
如图

![image](https://user-images.githubusercontent.com/24503039/40155540-e6a3695c-59c6-11e8-8031-220ebda31f34.png)

现有样本中存在同一法条重复存在的情况，比如 253这个法条在预测的label里出现了两次，实际预测的时候也要预测两次吗？我感觉是不是[253, 266]就足够了吧？

![image](https://user-images.githubusercontent.com/24503039/40155629-58397d4a-59c7-11e8-8517-e6c5a96972f2.png)

查看原始文书后，发现是由于原始文书涉及到了 253条不同款，出现了重复，所以标注数据中也出现了重复。

**Comment by xcjthu** [comment]
我们已经根据近期提出的问题，修正了一版数据，会在近两天公布，请关注官网通知
