### ISSUE TITLE
关于环境问题，每个人依赖库不同，或者同一个库版本不同，请问主办方如何解决啊？

### ISSUE THREAD

**Issue by tongjinle123** [thunlp/CAIL#17]
我用的是pytorch 0.4.0 和0.3.1比改动很大，其他库也有版本上的差别，是必须统一到官方的吗？我的代码已经写完了，这个比赛不应该，因为版本问题造成阻碍吧。。。

**Comment by haoxizhong** [comment]
pytorch这个问题提交模型的时候可以选择版本了（在做了），所以不用担心这个问题（只是还没做好）。
