### ISSUE TITLE
label 问题

### ISSUE THREAD

**Issue by congqinghe** [thunlp/CAIL#18]
你还是没有理解我的意思：
accu 文件里面的label其中一个是这样的：组织、强迫、引诱、容留、介绍卖淫
而你们给我们的训练集的label是这样的：'[组织、强迫、引诱、容留、介绍]卖淫'
里面的两个"[]" 这东西  我们提交的时候是要呢 还是不要呢

**Comment by congqinghe** [comment]
train中的    拒不执行[判决、裁定]"  在accu中只能找到    拒不执行判决、裁定 这一个label   而不能找到
    拒不执行判决 或者  拒不执行裁定

**Comment by xcjthu** [comment]
我们已经根据近期提出的问题，修正了一版数据，会在近两天公布，请关注官网通知
