### ISSUE TITLE
Baseline系统结果什么时候公布

### ISSUE THREAD

**Issue by enddddmaster** [thunlp/CAIL#19]
如题

**Comment by andrewpiggy** [comment]
+1，马上就到第一个截止日期6/5了。

**Comment by WeiyingWang** [comment]
同问，一直在等待baseline

**Comment by xcjthu** [comment]
已经在官网上公布，请查看大赛公告
任务一71.33, 任务二68.50, 任务三47.64，总成绩187.47。

**Comment by ax4** [comment]
@xcjthu 官网上的 baseline 公告，能否发一下链接？貌似现在找不到这个公告了😂？

**Comment by xcjthu** [comment]
官网的 大赛说明 已经更新，公告是 《关于模型测试提交系统改进的通知》中提到了baseline
