### ISSUE TITLE
对于涉及多同样法条无法训练的问题

### ISSUE THREAD

**Issue by luchenue** [thunlp/CAIL#21]
在训练集中存在着多同样法条出现多次的问题，如:
"relevant_articles": [205, 205, 205]
"relevant_articles": [205, 205]

我理解是这个案例可能涉及205中多个子条目，但是所给数据没具体是指出是哪个子条目
导致就算205只有3个子条目，[205, 205]可能是3种不同的标签(即205A_205B 205B_205C 205A_205C)

此处是否会更新下数据？或者评测时全部只按一个205做评测？

**Comment by xcjthu** [comment]
我们已经根据近期提出的问题，修正了一版数据，会在近两天公布，请关注官网通知
