### ISSUE TITLE
可能的数据泄露问题

### ISSUE THREAD

**Issue by raven4752** [thunlp/CAIL#23]
你们使用的数据都是网上可以爬到的，如果有人拿爬到的全部数据训练模型，是否存在数据泄露的风险？因为最后第一第二总分可能只差一点点，那数据泄露导致的分数提高会不会在计算最终排名时起到决定性作用？建议计算最终得分不考虑初赛分数。

**Comment by luchenue** [comment]
反正是提交代码，评测数据集正式比赛时都没有必要公布的

**Comment by padeoe** [comment]
@luchenue 他说的是测试数据集是公开的，容易被参赛者获取到

**Comment by hanxiao** [comment]
裁判文书网的文案不是很好爬取，做了很多反爬和流量限制

**Comment by xcjthu** [comment]
裁判文书网的文书不是很好爬取，本身有很多反爬取的措施，并且我们在第一阶段使用的所有数据是在全量文书上进行筛选的得到的，并且设置了第二阶段封闭测试也是为了避免这样的问题出现
