### ISSUE TITLE
任务三的一个疑问？ 请管理员解释一下

### ISSUE THREAD

**Issue by Tswings** [thunlp/CAIL#25]
"term_of_imprisonment": {"death_penalty": true, "imprisonment": 12, "life_imprisonment": false｝
"term_of_imprisonment": {"death_penalty": false, "imprisonment": 79, "life_imprisonment": true｝

如上情况，我们是直接预测刑期呢，还是预测是否 死刑/无期？

**Comment by Tswings** [comment]
任务三的评价方法有两种，两个都预测，那相加score>1，还是优先预测 死刑/无期，都False，然后再预测刑期？

**Comment by xcjthu** [comment]
感谢你的提问，上述问题应该是我们在处理原始数据时出现的一些问题，已经在最新数据集中修复，请从官方网站上重新下载即可
