### ISSUE TITLE
是否会将三个任务评测部分的代码开源

### ISSUE THREAD

**Issue by hanxiao** [thunlp/CAIL#26]
其实主办方是否提供rnn/svm baseline倒不是很重要。反而，开源三个任务在evaluation时计算得分部分的代码很重要。虽然README.md中提供了计算公式，但不同人理解不同，有一份主办方写的evaluation还是比较保险一些。二是，如果evaluation代码中有什么不太合理的地方，开源后，大家也可以提交PR或讨论。

**Comment by congqinghe** [comment]
赞同

**Comment by brightmart** [comment]
+1

**Comment by xcjthu** [comment]
收到建议，我们会在今明两天公布evaluation tool，请关注github~

**Comment by haoxizhong** [comment]
已发布在[CAIL2018](https://github.com/thunlp/CAIL2018)中
