### ISSUE TITLE
数据中存在错误罪名、法条的问题

### ISSUE THREAD

**Issue by WeiyingWang** [thunlp/CAIL#31]
您好，我在初步处理数据的过程中发现了如下问题：

- 出现不应出现的罪名
例如 data_train.json 中 38160 条
 {"fact": "济南市天桥区人民检察院指控：2014年12月30       日22时许，被告人左某某酒后驾驶小型轿车，由东向西行驶至济南市天桥区二环北路与济泺路交叉口处等信号灯时睡着，后被执勤民警查获。民警对被告人左某某进行酒精 呼气测试，含量为106mg/100ml。被告人左某某在抽取血样之前脱逃。本案刑事立案后，被告人左某某于2015年10       月12日接公安机关电话传唤到案。", "meta": {"relevan    t_articles": [133], "accusation": ["危险驾驶", " 组织、强迫、引诱、容留、介绍]卖淫", "协助组织卖淫 "       ], "punish_of_money": 0, "criminals": ["左某某"],        "term_of_imprisonment": {"death_penalty": false, "       imprisonment": 36, "life_imprisonment": false}}}
**这里只有酒驾，完全没有卖淫问题**

- 罪名数与法条数不符
例如 data_train.json 36241行
{"fact": "经审理查明，2015年10月23日17时许，被告人龚某饮酒后驾驶贵CFW908号二轮摩托车在仁怀市茅坝镇杨柳村青年塘组高干子（地名）路段与潘某驾驶的贵CGQ658       号二轮摩托车相接触后发生抓扯，公安民警对龚某进行呼出气体酒精含量检测，结果为190mg／100ml。经对龚某进行抽血检测，其血液中检出乙醇含量为142.67mg／100ml ，属于醉酒后驾驶机动车。另查明，被告人龚某曾因犯×× 罪和××罪于1997年4月29日被浙江省高级人民法院二审判处××，缓期二年执行，剥夺政治权利终身。经多次减刑后 ，浙江省杭州市中级人民法院于2012年4月6日以（2012）浙杭刑执字第3715号刑事裁定书裁定予以假释。假释考验       期：2012年4月16日至2015年12月24日。上述事实，有受案登记表、户籍证明、证人证言、检验报告、血样提取登记表、辨认笔录及照片、生效刑事判决书、刑事裁定书、假释证明书、查获经过、情况说明等证据证实，且被告人在开庭审理过程中亦无异议，足以认定。", "meta": {"relevant_articles": [133], "accusation": ["破坏电力设备", "危险驾驶", "盗窃"], "punish_of_money": 0,  "criminals": ["龚某"], "term_of_imprisonment": {"d       eath_penalty": false, "imprisonment": 44, "life_im       prisonment": false}}}
**这里法条数目比罪名数目少，同时本法条完全不涉及盗窃和破坏电力设备的问题**

- 案件内容信息处理有问题
例1: data_train.json 44208
{"fact": "公诉机关指控，自2000年起，被告人张某某在珠海市斗门区井岸镇黄杨大道旁开始经营“养蜂场”，将生产的蜂蜜放在养蜂场门口进行散装销售。期间，张某某使用氯霉素、土霉素等喂养蜜蜂。2014年7月4日，珠海市工商行政管理局斗门分局和斗门区食品药品监督管理局联合对“养蜂场”进行检查，对张某某放在养蜂场门口销售的自产的6斤荔枝蜂蜜、12斤百花蜂蜜进行抽样检测。经珠海市出入境检验检疫技术中心检验，上述蜂蜜中含氯霉素， 不符合《中华人民共和国农业部公告第193号》的限量要求。2015年1月8日，被告人张某某被公安民警抓获归案。 针对以上指控的事实，公诉机关当庭宣读和出示了书证、 证人证言、被告人的供述与辩解、鉴定意见、扣押笔录等证据予以证实。公诉机关认为被告人张某某无视国法，违 反国家食品卫生管理规定，使用国家明令禁用的氯霉素饲养蜜蜂，致使其生产、销售的蜂蜜中含有氯霉素，其行为已经构成××罪，张某某在××考验期内犯新罪，依法应当撤销××，数罪并罚，提请本院依法判处。", "meta": {"relevant_articles": [144], "accusation": ["[生产、销售][有毒、有害]食品", "抢劫"], "punish_of_money":   7000, "criminals": ["张某某"], "term_of_imprisonment": {"death_penalty": false, "imprisonment": 30,  "life_imprisonment": false}}}
**文本中对于 新罪 是什么完全没有提及，而在罪名预测中则出现了；同时法条中有没有出现**
例2 data_train.json 66021
{"fact": "泸州市江1某区人民检察院指控：被告人杨某甲系泸州市凌峰通讯有限公司（以下简称凌峰公司）法定代表人。2006年，因凌峰公司与中国联合通信有限公司泸州分公司（以下简称联通公司）发生合同纠纷，联通公司向泸州市江1某区人民法院（以下简称江1某法院）提起诉讼。2007年1月9日，根据联通公司的请求，江1某法院查封了凌峰公司 的1211台手机、冻结了凌峰公司的中国建设银行泸州分行账户100万元。同月12日，因案外人提供房产担保，江1某法院查封了杨某甲、阮某某、徐某某、杨某乙、高某某等人的4套房产，同时解除了对凌峰公司的1211台手机的查封。之后 ，根据杨某甲的请求，江1某法院解除了对阮某某、徐某某、杨某乙、高某某等案外人所提供房产的查封，再次查封了 凌峰公司的1283台手机。其后，杨某甲继续销售上述已查封的手机，致使被查封的手机数量不断减少，货款未按要求提交法院。2008年5月，江1某法院作出（2007）江1某民初字第390号民事判决，判决凌峰公司支付联通公司707741.36元人民币。联通公司于该判决生效后向江1某法院申请强制执行，但被查封的1283台手机已全部灭失，该案至今无法执行。针对上述指控事实，公诉机关出示了书证，证人证言，被告人供述和辩解等证据，认为被告人杨某甲变卖已被司法机关查封的财产，情节严重，其行为已触犯《中华人民共和国刑法》××之规定，应当以非法处置查封、扣押、冻结的财产罪追究其刑事责任。诉请本院依法判处。", "meta": {"relevant_articles": [313], "accusation": ["拒不执行[判 决、裁定]"], "punish_of_money": 0, "criminals": ["杨某甲"], "term_of_imprisonment": {"death_penalty": fa       lse, "imprisonment": 18, "life_imprisonment": false}}}
**文中出现的“应当以非法处置查封、扣押、冻结的财产罪”没做处理，也没在法条、罪名中出现**

类似的问题还有很多，请主办方尽快清洗数据

**Comment by renjunxiang** [comment]
同意
valid数据中第十条
"criminals": ["连某某"], "term_of_imprisonment": {"death_penalty": false, "imprisonment": 14, "life_imprisonment": false}, "punish_of_money": 10000, "accusation": ["盗窃"], "relevant_articles": [264]}, "fact": "经审理查明：一、2016年8月16日早上，被告人连某某在保定市满城区精灵网吧二楼包厢内盗窃被害人李某某OPPOR7S手机一部。所盗手机已销售，赃款已挥霍。经保定市满城区涉案物品价格鉴证中心认定，被盗手机价值1982元。上述事实，被告人连某某在开庭审理过程中亦无异议，且有被害人李某某的陈述，涉案物品价格鉴证结论书，辨认笔录及照片，破案经过等证据证实，足以认定。二、2016年6月份一条下午，被告人连某某在保定市满城区现代网吧东侧一平房内盗窃被害人张某现金300元。所盗赃款已挥霍。上述事实，被告人连某某在开庭审理过程中亦无异议，且有被害人张某的陈述，辨认笔录及照片，破案经过等证据证实，足以认定。三、2016年8月22日晚，被告人连某某在保定市竞秀区秀兰城市美居小区北门口外孟某某经营的“爱车靓装”洗车店内盗窃行车记录仪两个及被害人李某经现金1700余元。行车记录仪被其扔掉，所盗赃款已挥霍。经保定市满城区涉案物品价格鉴证中心认定，被盗行车记录仪价值共计556元。上述事实，被告人连某某在开庭审理过程中亦无异议，且有被害人孟某某、李某经的陈述，涉案物品价格鉴证结论书，辨认笔录及照片，破案经过等证据证实，足以认定。四、2016年9月3日凌晨，被告人连某某在保定市千色网吧内盗窃被害人甄某某VIVOX6手机一部。所盗手机已销售，赃款已挥霍。经保定市满城区涉案物品价格鉴证中心认鉴定，被盗手机价值2202元。上述事实，被告人连某某在开庭审理过程中亦无异议，且有被害人甄某某的陈述，涉案物品价格鉴证结论书，辨认笔录及照片，破案经过等证据证实，足以认定。五、2015年9月23日下午，被告人连某某从保定市满城区野里村连某家里骗走金娃牌柴油三轮车一辆卖掉，所骗取三轮车已销售，赃款已挥霍。2016年9月份左右一天下午，连某某从保定市满城区野里村连某甲经营的石板厂骗走金娃牌柴油三轮车一辆卖掉，所骗取三轮车已销售，赃款已挥霍。2016年8月份左右一天下午，连某某从保定市满城区白堡村曹某某经营的鸡场骗走爱玛牌电动车一辆卖掉，所骗取电动车已销售，赃款已挥霍。经保定市满城区涉案物品价格鉴证中心认定，被盗两辆三轮车、一辆电动车价值分别为1700元、1500元、1250元。连某某父母已赔偿连某、连某甲、曹某某的经济损失。上述事实，被告人连某某在开庭审理过程中亦无异议，且有证人孙某某、连某某的证言，被害人连某、连某甲、曹某某的陈述，涉案物品价格鉴证结论书，辨认笔录及照片，破案经过等证据证实，足以认定。"}
该论述出现了“被告人连某某从保定市满城区野里村连某家里骗走金娃牌柴油三轮车一辆卖掉，所骗取三轮车已销售，赃款已挥霍。2016年9月份左右一天下午，连某某从保定市满城区野里村连某甲经营的石板厂骗走金娃牌柴油三轮车一辆卖掉，所骗取三轮车已销售，赃款已挥霍。”应属于诈骗，我的预测结果是正确的['诈骗', '盗窃']，但是数据集中仅有['盗窃']。
请主办方严格控制数据集的准确性，因为该比赛是多目标检测，并且数据集存在严重的非平衡，罪名错误和不全将严重影响到多目标的置信度。由于数据集的不严谨，按照置信度>0.5来预测罪名我的准确率只有0.68，按照得分最高作为罪名（我只判断一个罪名）的准确率有0.79。

**Comment by xcjthu** [comment]
@renjunxiang 关于你提出的这个问题，按照判决文书原文，真实的判定结果为 盗窃罪
具体的可以查看文书全部原文 http://wenshu.court.gov.cn/content/content?DocID=04b73934-374e-4ced-ab0f-a79b00afd79e

**Comment by xcjthu** [comment]
@WeiyingWang 非常感谢问题的提出，关于数据的清洗和整理问题我们也在尽力进行清洗，减少错误的出现。因为有时候文书的格式不同地区的不太一样，我们也无法保证全部数据都为准确无误的。
对于提出的错误我们会进行检查。

提到的第3条，“新罪”只是一个代词，我们不会修改文书的原文内容
提到的第4条，根据文书原文，被告人所被判处的罪名 只有  犯拒不执行裁定罪

**Comment by renjunxiang** [comment]
这个我清楚，但是作为比赛，我认为数据应该是应该经过处理的。我上网查过，诈骗罪可能还和金额有关系，5000即可判定诈骗罪，他骗取的三辆车总额肯定超过5000。换一个角度，从数据的层面来说，我们训练模型的目的 **就是让机器能从不同的罪名中总结规律从而提高定罪的准确性，也许不同法官判定标准不同，但是机器是一样的** 。如果你的训练集标签都有不同的标准，那么如何让机器去统一的定罪呢。
个人一些小小的看法，我还是很尊重法官判决的。

**Comment by xcjthu** [comment]
嗯，您提出的问题确实是可能存在的，但是一般法官的判决结果都是在一定范围内进行的，不会有非常大的差距。但是对于这一届的比赛所使用的数据都是裁判文书网上公开的所有的真实的数据，我们是严格按照文书原文进行处理的。我们会减少由于清洗和处理造成的问题。
并且，我们会在之后的比赛中，考虑增加人工的统一标注，减少这类的情况出现

**Comment by WeiyingWang** [comment]
@xcjthu 您好，关于第四条，我知道“新罪”只是在指代，但是最终的罪名中出现了之前完全没有提及到的“抢劫”，我猜测这个抢劫会不会就是“新罪”。但是“抢劫”根据已有文本完全预测不出来。
另外我仅仅是举了一些例子，还有其他法条存在错误的情况，可能也需要多多注意一下。清洗数据辛苦了！

**Comment by andrewpiggy** [comment]
我分析了一下数据，发现罪名和法条跟事实描述不相关的情况还不少的，我们是应该当做feature来学习，还是应该当做噪音来过滤啊？

另外，”之后的比赛会减少这种情况“指的是后面的150w数据吗？
