### ISSUE TITLE
数据中存在的推理问题

### ISSUE THREAD

**Issue by lx865712528** [thunlp/CAIL#35]
您好，我在初步分析数据的过程中发现了以下问题：

- 被害人高某乙受伤经医院抢救无效，于2014年4月9日17时许死亡。经鉴定，高某乙系创伤性、失血性休克死亡；王某甲所受之伤为轻伤一级；王某乙所受之伤为轻伤二级；李某所受之伤为轻微伤。公诉机关认为，被告人王某丁伙同王4某等人故意伤害他人身体，致一人死亡，二人受轻伤，一人受轻微伤，其行为触犯了《中华人民共和国刑法》××××，犯罪事实清楚，证据确实、充分，应当以××追究其刑事责任。王某丁在共同犯罪中其次起次要作用，是**从犯**，依法应当从轻、减轻或者免除处罚；其到案后如实公式供述自己的罪行，是**坦白**，依法可从轻处罚。根据《中华人民共和国刑事诉讼法》××的规定，特对被告人王某丁提起公诉。请依法判处。

- 上海市公安局浦东分局出具的案发经过表格，证实被告某某的身份情况。"}××追究其刑事责任，系共同犯罪。被告人赵某犯罪时已满16周岁未满18周岁，根据《中华人民共和国刑法》××××的规定，属**未成年人犯罪**，应当从轻或者减轻处罚。

其中的**从犯**，**坦白**，和**未成年**都会影响最后量刑的计算，在训练数据中这种重要的信息点会直接出现在文本中，那么请问**在最终的测试数据中是否能保证这些点也是直接出现？还是在最终的测试数据中需要隐含推理出这些信息点呢？**

这是一个很重要的问题，牵涉到方法需要设计的功能范围，请主办方尽快明确。

**Comment by haoxizhong** [comment]
如果在我们下发的数据中，事实部分中有这些信息，那么最终测试数据里面就会有，否则就没有。
