### ISSUE TITLE
评价方法: 针对多类别而不是二分类的TP,FP,FN

### ISSUE THREAD

**Issue by brightmart** [thunlp/CAIL#6]
评价方法里，TP,FP,FN用的是二分类中的0，1来解析。那在多类别下，而不是二分类中，TP,FP,FN到底是什么呢，怎么理解？

另外N是什么

**Comment by xcjthu** [comment]
TP,FP,FN  是评价指标的缩写形式，为了方便表示后面的公式而设置的
FN：False Negative,被判定为负样本，但事实上是正样本。
FP：False Positive,被判定为正样本，但事实上是负样本。
TN：True Negative,被判定为负样本，事实上也是负样本。
TP：True Positive,被判定为正样本，事实上也是证样本。

**Comment by haoxizhong** [comment]
举个例子，对于第一个任务，是个多分类问题，N指的就是这个多分类任务的分类数量。对于这N个分类，单独考虑其中某一个就是一个二分类问题，这里TP等值都是定义在这一个二分类问题上的。然后根据每一类的TP、FP等值，我们可以计算你在N个分类问题上的宏平均分数和微平均分数，从而得到你最终的分数。

**Comment by myskety** [comment]
您好，我们现在面对的是多标签分类问题，对于某一个事实描述，可能涉及到多个罪名标签，比如盗窃和故意杀人，现在如果我的模型仅仅预测出故意杀人，请问这种情况下如何计算F值？
