### ISSUE TITLE
添加依赖环境

### ISSUE THREAD

**Issue by tongjinle123** [thunlp/CAIL#9]
您好，请添加依赖环境：
pytorch==0.4.0
pyltp==0.2.1
sklearn==0.19.1
allennlp==0.4.0

**Comment by tongjinle123** [comment]
看到列表中有0.3.1 的pytorch 但是我的代码是按照0.4.0 写的啊

**Comment by xcjthu** [comment]
我们会在上传模型的地方增加冲突环境选择，避免出现此类情况
